user:
  outputs:
    default:
      keyfile_json:
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        auth_uri: https://accounts.google.com/o/oauth2/auth
        client_email: healthcare-data-project@healthcare-data-project-499612.iam.gserviceaccount.com
        client_id: '109744871962055247846'
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/healthcare-data-project%40healthcare-data-project-499612.iam.gserviceaccount.com
        private_key: '-----BEGIN PRIVATE KEY-----

          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDUU2RTp7/xPZ/5

          mLKTNLMIPkl7C3E382BC13RWqYoYkdIva+SRiBQjsO9Q3qB3FsXWZZkDH3zkAyDa

          4eKSghuQWJga9uAg5+E5N+xOzu5nrnEmksJomr/LnNAquYB4TyEF9omxmPA0nw35

          A99VMYC1kPnbNAiTPTt0Jf1iPyGYQ8YcBwFpz4olO1NgKJw+/rwTJJiM0YzrxldO

          a35n/P2l4R1wVI+65B2DZiMTtJhHvPs/aYtMDRYrlljFamuA15szVunYOeW4OH3b

          4GD5tTEHb77VhdkaIg36fLYH2OkPpo57l1pWH9S7YqPKGd2+MnTzDP1YsI4MAG1q

          66RVjtoPAgMBAAECggEARoJQ8VTmMVMRIn56Ytcf0w94MGPK29U29Mt+x16yzNjz

          7yqJs2h4o6eYuYbMy+9kkH+ZsgdNXpzJVtanepa5V5SMInw0TskiKnGvSDaAxi6Q

          Rcp7w+gL5C51lJKYnptMcKH/9NnAfwEIz1ZhXnW7c9AqoQglBtxRN498Fxm26syP

          +TqxfRSTzBs5jIRot2O24N4RIToHQDXaMBLum3n/tp5plMFUaiE2CDNdX+TFLK0h

          9XsSnwmYvpaZWRNkhbWdGbsJ5NO6mBGwxkstspI3G2wFCUv7ajgOAP7U4p+2NTzK

          2vnf1BPsgr8nVvuM1PjPAk32YK2m/FNJnrpZ1TMMsQKBgQDxEJ93c3H5jc4enaGp

          knYDWmHPAXhkjgfIoBjGS0Dlmf+matUc8L0WuM+vKqe+uQJ9ErTj0NGSD1Vcwwoc

          9iDtRdon4xbaCCwpe/goJMiSobpW6w5MevTLi21yI5qwMsSHZyMhCFmUqMhJKKOD

          QKKhibYYPqdHZjQI0vpA45WUMQKBgQDhevSDgFkww3pibpmW2ZSg1hwYsuAW1LZW

          GkllIG1Q7hQB5CtBChBwpV2RIcxV/DaQwK53PaPLxGq4OVjNDLnzos24ObTvVHWk

          1p40YGcjW02L8RDSeQ9MCB0I9FtiVU4CWp3Rx6PcU/AEBP6iPMzMcNCmUOdNk4KI

          7b3BP0cCPwKBgFh9KpxVg1wA4s24PVSaz7kxXz/2oTQAMvlBU3bOvvbJTd/PzYT/

          FdoWYx5AwSywiypQSJhr2dIM0N/pNHgnHTUb9BW6NXQ5lcRwnkpWHk49EcLALBKE

          /AEPoFBKo4jUSfIOOQXyI7f/MO4x/bu7aTd07qP9s7fw21712ykgoZKxAoGAZjiG

          x2MVjDziq+M2MCQ99Fh87lmRq+gNLaXHJlh4FpuIaH8XeOnmIBtn+tbWuxiXaDJi

          Jd7E9ij6tMAS2Qru9lwVZXKL64BfwTYnDNmziFzpIAtOtAx7+d0nxJp7H25K6lhI

          egVG7SkEg937znM/6WMvxGajJhE8uXUGdKiKOaMCgYEAy4KhD2rjILEZI/Q1YC1N

          jOl5F5+CseRUjfBxwVsS35BfdrRNPRLg+mZ5uUa7QyCbUYzc0Wd1L1KXTOiGI6sW

          mtCMCqydE625/Be7JGWgLximpeCkFtlnaONevx64WScyepA7aVQ247rNBA3VXMKW

          K9mL8E/SYZGn3ZgErdM5vvU=

          -----END PRIVATE KEY-----

          '
        private_key_id: 9deb30aec3296a34deee3121e92e2541fc783db7
        project_id: healthcare-data-project-499612
        token_uri: https://oauth2.googleapis.com/token
        type: service_account
      location: europe-west3
      method: service-account-json
      project: healthcare-data-project-499612
      schema: dev_healthcare_project_data
      scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
      - https://www.googleapis.com/auth/userinfo.email
      target_name: default
      threads: 4
      type: bigquery
  target: default
